export const REQUEST_SEARCH_RESTORANT = 'REQUEST_SEARCH_RESTORANT'
export const REQUEST_SEARCH_RESTORANT_SUCCESS = 'REQUEST_SEARCH_RESTORANT'
export const REQUEST_SEARCH_RESTORANT_FAILED = 'REQUEST_SEARCH_RESTORANT_FAILED'

export function requestSearchRestorant(){
    return{
        type:REQUEST_SEARCH_RESTORANT
    }
}